use Mix.Config

config :ripley,
  http_api: HTTPoison,
  subreddits: [
    %{name: "Ada", url: "https://www.reddit.com/r/ada/"},
    %{name: "Agda", url: "https://www.reddit.com/r/agda/"},
    %{name: "Assembly", url: "https://www.reddit.com/r/asm/"},
    %{name: "C", url: "https://www.reddit.com/r/C_Programming/"},
    %{name: "Clojure", url: "https://www.reddit.com/r/Clojure/"},
    %{name: "COBOL", url: "https://www.reddit.com/r/cobol/"},
    %{name: "CoffeeScript", url: "https://www.reddit.com/r/coffeescript/"},
    %{name: "Crystal", url: "https://www.reddit.com/r/crystal_programming/"},
    %{name: "C#", url: "https://www.reddit.com/r/csharp/"},
    %{name: "C++", url: "https://www.reddit.com/r/cpp/"},
    %{name: "D", url: "https://www.reddit.com/r/d_language/"},
  	%{name: "Dart", url: "https://www.reddit.com/r/dartlang/"},
  	%{name: "Elixir", url: "https://www.reddit.com/r/elixir/"},
  	%{name: "Elm", url: "https://www.reddit.com/r/elm/"},
  	%{name: "Erlang", url: "https://www.reddit.com/r/erlang/"},
  	%{name: "Forth", url: "https://www.reddit.com/r/Forth/"},
  	%{name: "Fortran", url: "https://www.reddit.com/r/fortran/"},
  	%{name: "F#", url: "https://www.reddit.com/r/fsharp/"},
  	%{name: "Go", url: "https://www.reddit.com/r/golang/"},
  	%{name: "Groovy", url: "https://www.reddit.com/r/groovy/"},
    %{name: "Hack", url: "https://www.reddit.com/r/hacklang/"},
  	%{name: "Haskell", url: "https://www.reddit.com/r/haskell/"},
  	%{name: "Haxe", url: "https://www.reddit.com/r/haxe/"},
  	%{name: "Idris", url: "https://www.reddit.com/r/Idris/"},
  	%{name: "Java", url: "https://www.reddit.com/r/java/"},
  	%{name: "JavaScript", url: "https://www.reddit.com/r/javascript/"},
  	%{name: "Julia", url: "https://www.reddit.com/r/Julia/"},
  	%{name: "Kotlin", url: "https://www.reddit.com/r/Kotlin/"},
  	%{name: "Lisp", url: "https://www.reddit.com/r/lisp/"},
  	%{name: "Lua", url: "https://www.reddit.com/r/lua/"},
  	%{name: "Nim", url: "https://www.reddit.com/r/nim/"},
  	%{name: "Objective C", url: "https://www.reddit.com/r/ObjectiveC/"},
    %{name: "OCaml", url: "https://www.reddit.com/r/ocaml/"},
  	%{name: "Pascal", url: "https://www.reddit.com/r/delphi/"},
  	%{name: "Perl", url: "https://www.reddit.com/r/perl/"},
  	%{name: "PHP", url: "https://www.reddit.com/r/PHP/"},
  	%{name: "Pony", url: "https://www.reddit.com/r/ponylang/"},
  	%{name: "Prolog", url: "https://www.reddit.com/r/prolog/"},
  	%{name: "Python", url: "https://www.reddit.com/r/Python/"},
  	%{name: "Ruby", url: "https://www.reddit.com/r/ruby/"},
  	%{name: "Rust", url: "https://www.reddit.com/r/rust/"},
  	%{name: "Scala", url: "https://www.reddit.com/r/scala/"},
  	%{name: "Scheme", url: "https://www.reddit.com/r/scheme/"},
  	%{name: "Scratch", url: "https://www.reddit.com/r/scratch/"},
    %{name: "Smalltalk", url: "https://www.reddit.com/r/smalltalk/"},
  	%{name: "Swift", url: "https://www.reddit.com/r/swift/"},
  	%{name: "TCL", url: "https://www.reddit.com/r/Tcl/"},
  	%{name: "TypeScript", url: "https://www.reddit.com/r/typescript/"},
    %{name: "Vala", url: "https://www.reddit.com/r/vala/"},
  	%{name: "Visual Basic", url: "https://www.reddit.com/r/visualbasic/"},
    %{name: "Wolfram", url: "https://www.reddit.com/r/wolframlanguage/"},
    %{name: "Xojo", url: "https://www.reddit.com/r/xojo/"},
  ]
